try adding tag functionality

diff --git a/build/tools/make_release b/build/tools/make_release
--- a/build/tools/make_release
+++ b/build/tools/make_release
@@ -22,6 +22,13 @@ PG_USER=NONE # -U
 PG_PASS=NONE # -P
 PG_PORT=NONE # -O
 
+decimalize_version () {
+    VERSION=`echo $VERSION | sed 's/^rel_\([0-9]\+\)_\([0-9]\+\)_\([0-9]\+\)_\(.\+\)$/\1.\2.\3-\4/'`
+    VERSION=`echo $VERSION | sed 's/^rel_\([0-9]\+\)_\([0-9]\+\)_\([0-9]\+\)$/\1.\2.\3/'`
+    VERSION=`echo $VERSION | sed 's/^rel_\([0-9]\+\)_\([0-9]\+\)_\(.\+\)$/\1.\2-\3/'`
+    VERSION=`echo $VERSION | sed 's/^rel_\([0-9]\+\)_\([0-9]\+\)$/\1.\2/'`
+}
+
 while getopts ":hv:f:F:nptbriCH:D:U:P:O:" opt; do
     case $opt in
         v)
@@ -124,13 +131,15 @@ fi
 if [ "$VERSION" == "AUTO" ]; then
     # Auto-pick version based on branch name
     echo AUTO VERSION
-    VERSION=`echo $GIT_BRANCH | sed 's/^rel_\([0-9]\+\)_\([0-9]\+\)_\([0-9]\+\)_\(.\+\)$/\1.\2.\3-\4/'`
-    VERSION=`echo $VERSION | sed 's/^rel_\([0-9]\+\)_\([0-9]\+\)_\([0-9]\+\)$/\1.\2.\3/'`
-    VERSION=`echo $VERSION | sed 's/^rel_\([0-9]\+\)_\([0-9]\+\)_\(.\+\)$/\1.\2-\3/'`
-    VERSION=`echo $VERSION | sed 's/^rel_\([0-9]\+\)_\([0-9]\+\)$/\1.\2/'`
+    VERSION=`echo $GIT_BRANCH`
+    decimalize_version
     if [ "$VERSION" = "$GIT_BRANCH" ]; then
-        echo "AUTO VERSION FAILED."
-        exit 1
+        VERSION=`git tag --points-at HEAD`
+        decimalize_version
+        if [ "$VERSION" = "$GIT_BRANCH" ]; then
+            echo "AUTO VERSION FAILED."
+            exit 1
+        fi
     fi
 fi
 SHORT_VERSION=`echo $VERSION | grep -o '^[0-9]\+\.[0-9]\+'`
